### ISSUE TITLE
[8.5] Create debug report for users #1696

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#1]
**Original issue**
#1696

**Suggestion**
Include a button on the bottom right next to Help button. It opens a popup where the user can decide to create an extensive of console report. After choosing one of the two options, the data is collected and then displayed in the popup. Now the user can copy the content and use it to show it to support or anyone else interested.

- Console report
Get the last 20 entries of the browser debug console (see screenshot for an example) and display them in a text area within the Popup
![image](https://user-images.githubusercontent.com/33128181/44978310-b56cca00-af6a-11e8-913e-94deee455829.png)

- Extensive report
Console report, a screenshot of the current visible Tab (if possible), plus the users account name.

**Pointers**
Popups are realized via Modals, see https://github.com/blockchainprojects/bitshares-ui/blob/1097a7d3b544975e26e80f0b118db314c08b84d0/app/components/Layout/Footer.jsx#L339 as an example. The debug report popup should be available throughout the UI, i.e. it should also be in the Footer.

**Tasks**
- [x] Get familiar how Popups work
- [x] Include a new button that opens a Popup next to Help
- [ ] Present the user three choices: Advanced report, Console report and Cancel
- [x] Click Console report fills the textarea and shows a button that selects the whole text and copies it to clipboard

**Comment by yuriikarpenkoo** [comment]
We have chosen the following method for catching console.log, console.warn, console.info, console.error - https://stackoverflow.com/questions/19846078/how-to-read-from-chromes-console-in-javascript
Also, the unsuccessful requests are caught using the React method - componentWillCatch.

We keep 20 last records in the local.storage and use them for the further actions. The records are updated automatically: when the new error is received, it is recorded to the first place and all records move 1 step forward, the last (oldest) record from the list is deleted).
When we click the ‘Copy errors’ button in the modal window, the data from the local.storage is copied to the clipboard.

For the screenshots the following approach was chosen: we take a screenshot of the window content using canvas https://html2canvas.hertzen.com/. It returns data in the base64 format. After that we convert the base64 format to pdf-document using the following library https://parall.ax/products/jspdf. The pdf-file is automatically uploaded to the user’s computer.

**Comment by sschiessl-bcp** [comment]
Current implementation looks much better
![image](https://user-images.githubusercontent.com/33128181/46194849-de327600-c302-11e8-8b32-a5089492a2fe.png)

Looking at the workflow I would like that the initial state of the modal contains an explanatory text (I will include that one). The two buttons are then "Take Screenshot" and "Show Log".

"Take Screenshot" stays as is, when user clicks on "Show Log" the component with the explanatory text disappears, and the textarea with the logs appears. The button "Copy Log" can be on the top right or bottom right of the textarea (not within the choices in the bottom).

**Comment by VerevkinAlexander** [comment]
I deleted all new .catch()

**Comment by sschiessl-bcp** [comment]
PR accepted

**Comment by sschiessl-bcp** [comment]
@VerevkinAlexander 

I updated this to the latest modal structure (we switched to ant.design). Something doesnt work correctly anymore when capturing screenshot. I assume its something with the implicit use of content in shouldComponentUpdate. 

Can you please have a look?

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
I found reasons of the issue and fixed it also I fixed the issue with modal rendering and added the method for ok button in the modal.
