### ISSUE TITLE
Implement In-Ram switch for localStorage

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#11]
The SettingsStore and others are currently linked to "settings_vX" in the localStorage. Other places in the UI also load from localStorage and might save into it.

**Tasks**
- [x] Add a single point of query for all localStorage calls: Create a new class that wraps all loading and saving to localStorage, and use it consistently in UI, name for example: bitSharesStorage
- [x] Add a method to bitSharesStorage that turns off persisting the data
- [x] If persisting is turned off, no changes will be propagated to the underlying localStorage

**Comment by sschiessl-bcp** [comment]
Implemented in branch 12_Private_Login
