### ISSUE TITLE
[8.5] Private Login - Cloud Login

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#12]
**Original issue**
#1724 and related #1360

**Dependencies**
#11 must be finished

**Tasks**
- [x] Add new Settings option: "remember_user", which is connected to "Remember Me". 
- [x] Include a "Remember Me" toggle in Login modal (bottom right corner). Persist the setting into localStorage on every login
![image](https://user-images.githubusercontent.com/33128181/45623232-eaa70b00-ba86-11e8-82f3-d9c7977b4736.png)

All following tasks only apply to Cloud login mode.
- [ ] If the user logs out, and "Remember Me" was not set on login, check if the account in bitSharesStorage is the account currently unlocked. If so, remove all account related bitSharesStorage entries (account name)
- [x] If the user logs in, and "Remember Me" is not checked, turn off persisting in bitSharesStorage

**Comment by sschiessl-bcp** [comment]
PR #14 accepted
